### ISSUE TITLE
why gatsby 🤦 💀 

### ISSUE THREAD

**Issue by nexxeln** [asheeeshh/gatsby-starter-biolink#1]

**Comment by asheeeshh** [comment]
lmfao, no reason, just wanted to try it and make a starter template, had some free time 😂

**Comment by nexxeln** [comment]
fair enough, its very overengineered.

**Comment by asheeeshh** [comment]
yes, ig making it with some svelte or vue would have been much better option rathe than using nextjs/gatsby or anything

**Comment by asheeeshh** [comment]
I was thinking of exploring astro but I kinda procrastinated ig 🥶

**Comment by nexxeln** [comment]
lol
